apiVersion: v1
kind: Pod
metadata:
  name: nginx-hello
  namespace: hwh-test 
  labels:
    app: nginx-hello 
spec:
  restartPolicy: OnFailure
  containers:
  - name: bogus 
    image: quay.io/hu_weihua/hello-world-nginx:v1.0
    command: [ "/bin/sh", "-c", "--" ]
    args:
    - set -xe;
      echo 'Welcome to basic test pod: nginx-hello';
      sleep 36000;
exit 0;
