apiVersion: v1
kind: Pod
metadata:
  name: two-pvs-feed-data
  namespace: hwh-test
  labels:
    app: two-pvs-feed-data
spec:
  restartPolicy: OnFailure
  containers:
  - name: bogus 
    image: alpine
    command: [ "/bin/sh", "-c", "--" ]
    args:
    - set -xe;
      cd /data/vol/1;
      echo 'line 1' >  file;
      echo 'line 2' >> file; 
      echo 'line 1' >  file1; 
      dd if=/dev/urandom of=/data/vol/1/binary.rnd bs=1048576 count=1; 
      sha256sum binary.rnd > binary.sha256; 
      cd /data/vol/2;
      echo 'line 1' >  file; 
      echo 'line 2' >> file; 
      echo 'line 1' >  file1; 
      dd if=/dev/urandom of=/data/vol/2/binary.rnd bs=1048576 count=1; 
      sha256sum binary.rnd > binary.sha256;
      exit 0;
    volumeMounts:
    - name: testpv1
      mountPath: /data/vol/1
    - name: testpv2
      mountPath: /data/vol/2
  volumes:
  - name: testpv1
    persistentVolumeClaim:
      claimName: hwh-pvc-1
  - name: testpv2
    persistentVolumeClaim:
      claimName: hwh-pvc-2
